services:
  - type: web
    name: ecotrack-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
