import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function generateCarbonReport(entry, userName) {
  const doc = new jsPDF();
  const date = new Date(entry.date).toLocaleDateString('en-IN');

  // Header
  doc.setFontSize(20);
  doc.setTextColor(22, 163, 74); // green
  doc.text('EcoTrack Carbon Report', 20, 25);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Name: ${userName}`, 20, 35);
  doc.text(`Date: ${date}`, 20, 42);
  doc.text(`Grade: ${entry.grade}`, 20, 49);

  // Divider
  doc.setDrawColor(22, 163, 74);
  doc.line(20, 54, 190, 54);

  // Results table
  doc.autoTable({
    startY: 60,
    head: [['Category', 'kg CO₂/year', '% of Total']],
    body: [
      ['Scope 1 — Direct Emissions', entry.breakdown.scope1?.toFixed(0) || 0, ((entry.breakdown.scope1 / entry.totalKg) * 100).toFixed(1) + '%'],
      ['Scope 2 — Electricity/Energy', entry.breakdown.scope2?.toFixed(0) || 0, ((entry.breakdown.scope2 / entry.totalKg) * 100).toFixed(1) + '%'],
      ['Scope 3 — Lifestyle/Indirect', entry.breakdown.scope3?.toFixed(0) || 0, ((entry.breakdown.scope3 / entry.totalKg) * 100).toFixed(1) + '%'],
      ['TOTAL', entry.totalKg.toFixed(0), '100%'],
    ],
    styles: { fontSize: 10 },
    headStyles: { fillColor: [22, 163, 74] },
    footStyles: { fontStyle: 'bold' }
  });

  const finalY = doc.lastAutoTable.finalY + 10;

  // Comparison
  doc.setFontSize(13);
  doc.setTextColor(30);
  doc.text('How you compare', 20, finalY);
  doc.autoTable({
    startY: finalY + 5,
    head: [['Benchmark', 'kg CO₂/yr', 'Your status']],
    body: [
      ['World Average', '4,000', entry.totalKg < 4000 ? '✓ Below' : '✗ Above'],
      ['India Average', '1,700', entry.totalKg < 1700 ? '✓ Below' : '✗ Above'],
      ['Paris Target', '2,000', entry.totalKg < 2000 ? '✓ On track' : '✗ Needs work'],
    ],
    styles: { fontSize: 10 },
    headStyles: { fillColor: [15, 116, 143] }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by EcoTrack — ecotrack-carbon-footprint-calculator.netlify.app', 20, 285);

  doc.save(`EcoTrack-Report-${date.replace(/\//g, '-')}.pdf`);
}
