import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generatePDFReport = (entry, user) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Helper to center text
  const centerText = (text, y) => {
    const textWidth = doc.getStringUnitWidth(text) * doc.internal.getFontSize() / doc.internal.scaleFactor;
    const textOffset = (pageWidth - textWidth) / 2;
    doc.text(text, textOffset, y);
  };

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  centerText('EcoTrack Carbon Report', 20);
  
  doc.setLineWidth(0.5);
  doc.line(20, 25, pageWidth - 20, 25);

  // User Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name     : ${user?.name || 'EcoTrack User'}`, 20, 35);
  doc.text(`Date     : ${new Date(entry.date || Date.now()).toLocaleDateString()}`, 20, 42);
  doc.text(`Report   : ${entry.reportTitle || 'Untitled Report'}`, 20, 49);

  // Results Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('RESULTS SUMMARY', 20, 65);
  doc.setLineWidth(0.2);
  doc.line(20, 67, 75, 67);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  const b = entry.breakdown || {};
  const s1 = b.scope1 || 0;
  const s2 = b.scope2 || 0;
  const s3 = b.scope3 || 0;

  doc.text(`Scope 1 (Direct Emissions)    : ${s1.toLocaleString()} kg CO2`, 20, 77);
  doc.text(`Scope 2 (Electricity/Energy)  : ${s2.toLocaleString()} kg CO2`, 20, 84);
  doc.text(`Scope 3 (Indirect/Lifestyle)  : ${s3.toLocaleString()} kg CO2`, 20, 91);
  
  doc.line(20, 96, pageWidth - 20, 96);
  
  doc.setFont('helvetica', 'bold');
  doc.text(`TOTAL                         : ${entry.totalKg.toLocaleString()} kg CO2/yr`, 20, 105);
  doc.text(`GRADE                         : ${entry.grade || 'N/A'}`, 20, 112);

  // Comparison
  doc.setFontSize(14);
  doc.text('COMPARISON', 20, 130);
  doc.line(20, 132, 60, 132);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  const worldDiff = ((entry.totalKg - 4000) / 4000 * 100).toFixed(0);
  const indiaDiff = ((entry.totalKg - 1700) / 1700 * 100).toFixed(0);
  
  const worldText = worldDiff > 0 ? `${Math.abs(worldDiff)}% above` : `${Math.abs(worldDiff)}% below`;
  const indiaText = indiaDiff > 0 ? `${Math.abs(indiaDiff)}% above` : `${Math.abs(indiaDiff)}% below`;
  const targetStatus = entry.totalKg < 2000 ? 'On track' : 'Needs work';

  doc.text(`World Average    : 4,000 kg  -> You are ${worldText}`, 20, 142);
  doc.text(`India Average    : 1,700 kg  -> You are ${indiaText}`, 20, 149);
  doc.text(`Paris Target     : <2,000 kg -> Status: ${targetStatus}`, 20, 156);

  // Top 3 Reduction Tips
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('TOP 3 REDUCTION TIPS', 20, 175);
  doc.line(20, 177, 85, 177);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const tips = entry.tips || [];
  let yPos = 187;
  
  if (tips.length > 0) {
    tips.forEach((tip, index) => {
      doc.text(`${index + 1}. ${tip.title} — saves ~${tip.estimatedSavingKg} kg/yr`, 20, yPos);
      yPos += 7;
    });
  } else {
    doc.text('No specific tips available for this record.', 20, yPos);
  }

  // Footer
  doc.setLineWidth(0.5);
  doc.line(20, 275, pageWidth - 20, 275);
  doc.setFontSize(10);
  doc.setTextColor(100);
  centerText('Generated by EcoTrack | ecotrack.app', 282);
  
  // Save PDF
  const filenameDate = new Date().toISOString().split('T')[0];
  doc.save(`EcoTrack-Report-${filenameDate}.pdf`);
};
